//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS_WFMDashboard_ICM_Order
    {
        public int Id { get; set; }
        public string ManagerName { get; set; }
        public int AgentNo { get; set; }
        public int Order { get; set; }
    }
}
