//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS_WFMDashboard_Repeating_Event
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string RepeatType { get; set; }
        public Nullable<int> RepeatEveryNumber { get; set; }
        public string RepeatOnDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> EndAfterOccurences { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RepeatSummary { get; set; }
        public string EndType { get; set; }
    }
}
