//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS_WFMDashboard_Event_Invitee
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string Email { get; set; }
        public Nullable<int> AgentNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
